### ISSUE TITLE
Play & Pause Buttons

### ISSUE THREAD

**Issue by SteveSonoa** [skonves/demo-react-portals#1]
In your demo at the React Meetup, you showed functional play & pause buttons from the primary page that controlled the pop-out window. How did you achieve that functionality? I can't duplicate it on this repo. Thank you - this was incredibly impressive!

**Comment by skonves** [comment]
I'm glad you liked it!  Make sure you're on the `window` branch.

If that's what you're doing, what browser and OS are you using?  (FWIW, I have only run the demo on OSX 10.13.3 and Chrome 66.)

**Comment by SteveSonoa** [comment]
Thank you! That was perfect, so I'm marking the issue closed. I'm on Ubuntu 17.10 running Chrome 67.0.3396.79 64-bit. Everything functions as intended. Thanks again for demoing this!
